---
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    name: Build OTP $${matrix.otp}}
    strategy:
      matrix:
        include:
          - otp: 25.1
          - otp: 24.3
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: set up beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args:
            OTP_VERSION: ${{matrix.otp}}
          push: true
          tags: ghcr.io/shortishly/docker-erlang:${{matrix.otp}}
